drop table FACT_VALUE;
drop table FACT;
drop table DIMENSION_VALUE_LINK;
drop table DIMENSION_VALUE;
drop table DIMENSION;

create table DIMENSION (
  ID serial not null,
  ID_EXT int not null,
  CODE char(4) not null,
  ALIAS varchar(25),
  MODE varchar(10) not null,
  STRUCTURE varchar(10) not null,
  TYPE varchar(15) not null,
  TEXT_CS varchar(255),
  TEXT_EN varchar(255),
  TEXT_BG varchar(255),
  primary key (ID)
);
ALTER TABLE DIMENSION ADD CONSTRAINT "UI_DIMENSION_CODE" UNIQUE (CODE);
ALTER TABLE DIMENSION ADD CONSTRAINT "UI_DIMENSION_ID_EXT" UNIQUE (ID_EXT);
ALTER TABLE DIMENSION ADD CONSTRAINT "C_DIMENSION_MODE" CHECK (MODE IN ('SINGLE', 'MULTI', 'VIRTUAL'));
ALTER TABLE DIMENSION ADD CONSTRAINT "C_DIMENSION_STRUCTURE" CHECK (STRUCTURE IN ( 'FLAT', 'TREE', 'VIRTUAL'));
ALTER TABLE DIMENSION ADD CONSTRAINT "C_DIMENSION_TYPE" CHECK (TYPE IN ('DIMENSION_VALUE', 'TIMESTAMP', 'STRING', 'INT', 'LONG', 'BIG_DECIMAL', 'DOUBLE'));

create table DIMENSION_VALUE (
  ID serial not null,
  ID_EXT int not null,
  CODE varchar(15) not null,
  ALIAS varchar(25),
  DIMENSION_ID int not null,
  PARENT_ID int,
  TEXT_CS varchar(255),
  TEXT_EN varchar(255),
  TEXT_BG varchar(255),
  primary key (ID)
);
ALTER TABLE DIMENSION_VALUE ADD CONSTRAINT "UI_DIMENSION_VALUE_ID_EXT" UNIQUE (ID_EXT, DIMENSION_ID);
-- TODO: ALTER TABLE DIMENSION_VALUE ADD CONSTRAINT "UI_DIMENSION_VALUE_CODE" UNIQUE (CODE);
ALTER TABLE DIMENSION_VALUE ADD CONSTRAINT "F_DIMENSION_ID" FOREIGN KEY(DIMENSION_ID) REFERENCES DIMENSION(ID);
ALTER TABLE DIMENSION_VALUE ADD CONSTRAINT "F_DIMENSION_PARENT_ID" FOREIGN KEY(PARENT_ID) REFERENCES DIMENSION_VALUE(ID);

create TABLE DIMENSION_VALUE_LINK (
  ID serial not null,
  OWNER_ID int not null,
  DIMENSION_ID int not null,
  VALUE_ID int not null,
  primary key (ID)
);
-- TODO: dimension-value -> link -> dimension-value
ALTER TABLE DIMENSION_VALUE_LINK ADD CONSTRAINT "F_LINK_OWNER_ID" FOREIGN KEY(OWNER_ID) REFERENCES DIMENSION_VALUE(ID);
ALTER TABLE DIMENSION_VALUE_LINK ADD CONSTRAINT "F_LINK_DIMENSION_ID" FOREIGN KEY(DIMENSION_ID) REFERENCES DIMENSION(ID);
ALTER TABLE DIMENSION_VALUE_LINK ADD CONSTRAINT "F_LINK_VALUE_ID" FOREIGN KEY(VALUE_ID) REFERENCES DIMENSION_VALUE(ID);

create table FACT (
  ID serial not null,
  ID_EXT int not null,
  CODE varchar(50),
  ALIAS varchar(50),
  NAME varchar(255),
  FACT_TYPE_ID int,
  PARENT_ID int,
  primary key (ID)
);
ALTER TABLE FACT ADD CONSTRAINT "UI_FACT_ID_EXT" UNIQUE (ID_EXT);
ALTER TABLE FACT ADD CONSTRAINT "F_FACT_TYPE_ID" FOREIGN KEY(FACT_TYPE_ID) REFERENCES DIMENSION_VALUE(ID);
ALTER TABLE FACT ADD CONSTRAINT "F_FACT_PARENT_ID" FOREIGN KEY(PARENT_ID) REFERENCES FACT(ID);

-- skutecna hodnota nebo odkaz na hodnotu z ciselniku
create table FACT_VALUE (
  ID serial not null,
  ID_EXT int,
  CODE varchar(5),
  ALIAS varchar(50),
  DIMENSION_ID int,
  FACT_ID int not null,
  DIMENSION_VALUE_ID int,
  VALUE varchar(50),
  VALUE_TYPE varchar(15) not null
);
ALTER TABLE FACT_VALUE ADD CONSTRAINT "C_FACT_VALUE_TYPE" CHECK (VALUE_TYPE IN ('DIMENSION_VALUE', 'TIMESTAMP', 'STRING', 'INT', 'LONG', 'BIG_DECIMAL', 'DOUBLE'));
ALTER TABLE FACT_VALUE ADD CONSTRAINT "F_DIMENSION_ID" FOREIGN KEY(DIMENSION_ID) REFERENCES DIMENSION(ID);
ALTER TABLE FACT_VALUE ADD CONSTRAINT "F_FACT_ID" FOREIGN KEY(FACT_ID) REFERENCES FACT(ID);
ALTER TABLE FACT_VALUE ADD CONSTRAINT "F_DIMENSION_VALUE_ID" FOREIGN KEY(DIMENSION_VALUE_ID) REFERENCES DIMENSION_VALUE(ID);