drop table FACT_VALUE;
drop table FACT;
drop table DIMENSION_VALUE;
drop table DIMENSION;

create table DIMENSION (
  ID int not null,
  CODE char(4) not null,
  ALIAS varchar(25),
  MODE varchar(10) not null,
  STRUCTURE varchar(10) not null,
  primary key (ID)
);
ALTER TABLE DIMENSION ADD CONSTRAINT "UI_DIMENSION_CODE" UNIQUE (CODE);
ALTER TABLE DIMENSION ADD CONSTRAINT "C_DIMENSION_MODE" CHECK (MODE IN ('SINGLE', 'MULTI', 'VIRTUAL'));
ALTER TABLE DIMENSION ADD CONSTRAINT "C_DIMENSION_STRUCTURE" CHECK (STRUCTURE IN ( 'FLAT', 'TREE'));

create table DIMENSION_VALUE (
  ID int not null,
  CODE varchar(5) not null,
  ALIAS varchar(25),
  DIMENSION_ID int not null,
  PARENT_ID int,
  primary key (ID)
);
ALTER TABLE DIMENSION_VALUE ADD CONSTRAINT "UI_DIMENSION_VALUE_CODE" UNIQUE (CODE);
ALTER TABLE DIMENSION_VALUE ADD CONSTRAINT "F_DIMENSION_ID" FOREIGN KEY(DIMENSION_ID) REFERENCES DIMENSION(ID);
ALTER TABLE DIMENSION_VALUE ADD CONSTRAINT "F_DIMENSION_PARENT_ID" FOREIGN KEY(PARENT_ID) REFERENCES DIMENSION_VALUE(ID);

create table FACT (
  ID serial not null,
  CODE varchar(50),
  ALIAS varchar(50),
  NAME varchar(255),
  PARENT_ID int,
  primary key (ID)
);
ALTER TABLE FACT ADD CONSTRAINT "F_FACT_PARENT_ID" FOREIGN KEY(PARENT_ID) REFERENCES FACT(ID);

-- skutecna hodnota nebo odkaz na hodnotu z ciselniku
create table FACT_VALUE (
  ID serial not null,
  CODE varchar(5),
  ALIAS varchar(50),
  DIMENSION_ID int,
  FACT_ID int,
  DIMENSION_VALUE_ID int,
  VALUE_VALUE varchar(50),
  TYPE varchar(15) not null
);
ALTER TABLE FACT_VALUE ADD CONSTRAINT "C_FACT_VALUE_TYPE" CHECK (TYPE IN ('DIMENSION_VALUE', 'TIMESTAMP', 'STRING', 'INT', 'LONG', 'BIG_DECIMAL', 'DOUBLE'));
ALTER TABLE FACT_VALUE ADD CONSTRAINT "F_DIMENSION_ID" FOREIGN KEY(DIMENSION_ID) REFERENCES DIMENSION(ID);
ALTER TABLE FACT_VALUE ADD CONSTRAINT "F_FACT_ID" FOREIGN KEY(FACT_ID) REFERENCES FACT(ID);
ALTER TABLE FACT_VALUE ADD CONSTRAINT "F_DIMENSION_VALUE_ID" FOREIGN KEY(DIMENSION_VALUE_ID) REFERENCES DIMENSION_VALUE(ID);